---
name: libblkid CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "CHANGES.txt"
      - "**/README.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "CHANGES.txt"
      - "**/README.md"

  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          - components: rustfmt
            task: fmt-ci
          - components: clippy
            task: clippy
          - components: cargo
            task: docs-ci
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: ${{ matrix.components }}
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libblkid-dev
      - name: Test ${{ matrix.task }} on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: make -f Makefile ${{ matrix.task }}

  # Ubuntu checks
  ubuntu-checks:
    strategy:
      matrix:
        task: [build, test]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install jq libblkid-dev
      - name: Run test on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: make ${{ matrix.task }}
      - name: Set toolchain to MSRV
        uses: stratis-storage/github-actions/set-rust-toolchain@HEAD
      - name: Run test on LOWEST SUPPORTED RUST TOOLCHAIN
        run: make ${{ matrix.task }}

  # MacOS checks
  macos-checks:
    strategy:
      matrix:
        task: [build, test]
    env:
      PKG_CONFIG_PATH: /opt/homebrew/opt/util-linux/lib/pkgconfig
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: brew install jq util-linux
      - name: Run test on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: make ${{ matrix.task }}
      - name: Set toolchain to MSRV
        uses: stratis-storage/github-actions/set-rust-toolchain@HEAD
      - name: Run test on LOWEST SUPPORTED RUST TOOLCHAIN
        run: make ${{ matrix.task }}

  general_checks:
    uses: stratis-storage/github-actions/.github/workflows/reusable_general.yml@master
    with:
      fedora-container-image-number: 43  # CURRENT DEVELOPMENT ENVIRONMENT
