---
name: libblkid nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 5 3 * * *

  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: cargo
          toolchain: 1.86.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libblkid-dev
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
      - name: Run audit check
        run: make audit

  checks-with-ci-repo:
    runs-on: ubuntu-22.04
    container:
      image: fedora:41  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - name: Install git for checkout action
        run: dnf install -y git
      - uses: actions/checkout@v4
        with:
          path: libblkid-rs
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          libblkid-devel
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: dtolnay/rust-toolchain@master
        with:
          components: cargo
          toolchain: 1.86.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
      - name: Check out ci repo
        uses: actions/checkout@v4
        with:
          path: ci
          repository: stratis-storage/ci
      - name: Run comparisons of -sys version specs with Fedora
        # yamllint disable rule:line-length
        run: |
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=rawhide make -f ../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f43 make -f ../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f42 make -f ../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f41 make -f ../Makefile check-fedora-versions
        working-directory: libblkid-rs/libblkid-rs-sys
      - name: Run comparisons of package version specs with Fedora
        # yamllint disable rule:line-length
        run: |
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=rawhide make -f Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f43 make -f Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f42 make -f Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f41 make -f Makefile check-fedora-versions
        working-directory: libblkid-rs

  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libblkid-dev
      - name: Do semantic version checks on libblkid-rs-sys
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          verbose: true
          rust-toolchain: 1.86.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
          manifest-path: libblkid-rs-sys
      - name: Do semantic version checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          verbose: true
          rust-toolchain: 1.86.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
